runtime: python39

instance_class: F2

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.main:app

handlers:
- url: /static
  static_dir: frontend-trackerfitness/build/static

- url: /.*
  static_files: frontend-trackerfitness/build/index.html
  upload: frontend-trackerfitness/build/index.html

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 4
